tasks:
  - init: |
      wget https://julialang-s3.julialang.org/bin/linux/x64/1.8/julia-1.8.1-linux-x86_64.tar.gz
      tar zxvf julia-1.8.1-linux-x86_64.tar.gz
      echo "export PATH='$PATH:/workspace/Math_for_ds/julia-1.8.1/bin'">> ~/.bashrc
      source ~/.bashrc
  - command: julia
